/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Setting the default buffer size */
#define DEFAULT_BLKSIZE 1048576

/* Setting the default TCP window settings */
#define DEFAULT_TCP_BUFFER_SIZE 0

/* Define to 1 if you have the `strtoll' function. */
#define HAVE_STRTOLL 1

/* Whether to build in mssftp functionality */
/* #undef MSSFTP */

/* Mssftp will use a GSI service cert */
/* #undef MSSFTP_GSI_SERVICE */

/* MSS to connect to */
#define MSSHOST "mss.ncsa.uiuc.edu"

/* Name of package */
#define PACKAGE "uberftp-client"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "Jason Alt <jalt@ncsa.uiuc.edu>"

/* Define to the full name of this package. */
#define PACKAGE_NAME "UberFTP (2.7 BETA 3)"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "UberFTP (2.7 BETA 3) 2.7_BETA_3"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "uberftp-client"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.7_BETA_3"

/* Version number of package */
#define VERSION "2.7_BETA_3"
